"""Bundle maps/*.json into frontend/maps.js so the page works from file://.

Run after adding or editing maps:
    python frontend/build_maps.py
"""
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "frontend", "maps.js")


def main():
    maps = []
    for path in sorted(glob.glob(os.path.join(ROOT, "maps", "*.json"))):
        with open(path, encoding="utf-8") as fh:
            maps.append(json.load(fh))
    body = json.dumps(maps, indent=2)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// Generated by build_maps.py - do not edit by hand.\n")
        fh.write(f"window.SOKOBAN_MAPS = {body};\n")
    print(f"wrote {len(maps)} maps to {OUT}")


if __name__ == "__main__":
    main()
